config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :districts, only: [:index] do
    resources :subscriptions, only: [:index, :new, :create, :destroy], shallow: true
    resources :customers, only: [:index, :new, :create]
  end
  resources :newspapers, only: [:index]
  resources :subscriptions, only: [] do
    member do
      post :change_status
      post :order_up
      post :order_down
    end
  end

  root to: 'districts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :district
  has_many :subscriptions, dependent: :destroy
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :subscription
end

app/models/district.rb
class District < ApplicationRecord
  has_many :customers, dependent: :destroy
  has_many :subscriptions, through: :customers
  validates :name, presence: true, uniqueness: true
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :newspaper
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_district, only: [:index, :new, :create]

  def index
    @customers = Customer.where(district_id: @district).order(:address)
  end

  def new
    # we need @district in our `simple_form_for` (views\customers\_form.html.erb), so we use before_action
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    # we need `district_id` to associate customer with corresponding district, so we use before_action
    @customer.district = @district
    @customer.save
    redirect_to district_customers_path
  end

  private

  def set_district
    @district = District.find(params[:district_id])
  end

  def customer_params
    params.require(:customer).permit(:name, :address, :delivery_note)
  end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  def index
    @districts = District.all
  end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  def index
    @newspapers = Newspaper.all
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_district, only: [:index, :new, :create]
  before_action :set_subscription, only: [:destroy, :change_status, :order_up, :order_down]
  before_action :set_subscriptions, only: [:index, :create, :destroy]

  def index
    # rewriting order-index from 2
    # we use even numbers as index for to make simpler changing subscription order
    i = 2
    @subscriptions.each do |item|
      item.order_index = i
      item.save
      i += 2
    end
  end

  def new
    @subscription = Subscription.new
    # we need @customers collection in our `simple_form_for` to show customers in dropdown box 
    @customers = Customer.where(district_id: @district).order(:address)
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.is_active = true

    # finding max value of order-index
    # order-index serves to order subscriptions in necessary way
    array_orders = []
    @subscriptions.each do |item|
      array_orders << item.order_index
    end
    @subscription.order_index = array_orders.max + 2

    @subscription.save
    redirect_to district_subscriptions_path
  end

  def destroy
    @subscription.destroy
    redirect_to district_subscriptions_path(@subscription.customer.district)
  end

  # changing subscription status: enabled or disabled
  def change_status
    @subscription.is_active == true ? @subscription.is_active = false : @subscription.is_active = true
    @subscription.save
    redirect_to district_subscriptions_path(@subscription.customer.district)
  end

  # changing subscription order
  def order_up
    @subscription.order_index = @subscription.order_index - 3
    @subscription.save
    redirect_to district_subscriptions_path(@subscription.customer.district)
  end

  # changing subscription order
  def order_down
    @subscription.order_index = @subscription.order_index + 3
    @subscription.save
    redirect_to district_subscriptions_path(@subscription.customer.district)
  end
  
  private

  def set_district
    @district = District.find(params[:district_id])
  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def set_subscriptions
    @subscriptions = Subscription.where(customer_id: Customer.where(district_id: @district)).order(:order_index)
  end

  def subscription_params
    params.require(:subscription).permit(:customer_id, :newspaper_id, :quantity, :is_monday,
      :is_tuesday, :is_wednesday, :is_thursday, :is_friday, :is_saturday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for [@district, @customer] do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :address, label: "Address:" %>
  </div>

  <div class="field">
    <%= form.input :name, label: "Name:" %>
  </div>

  <div class="field">
    <%= form.input :delivery_note, label: "Zustellung Beschreibung (BK, RO usw.):" %>
  </div>

  <div class="actions">
    <%= form.button :submit, "Speichern", class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/customers/index.html.erb
<div class="main">
  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="/districts">Bezirke</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/newspapers">Zeitungen</a>
    </li>
  </ul>
  <br>

  <table>
    <tr>
      <td><h4><p class="text-dark">Kunden des Bezirkes <%= @district.name %></p></h4></td>
      <td class="button_new"><p><%= link_to 'Neuen Kunden erstellen', new_district_customer_path, class: "btn btn-outline-secondary" %></p></td>
    </tr>
  </table>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th class="text-center">№</th>
        <th>Adresse</th>
        <th>Zust.Bes.</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% i = 0 %>
      <% @customers.each do |customer| %>
        <% i += 1 %>
        <tr>
          <td class="text-center"><%= i %></td>
          <td><%= customer.address %></td>
          <td><%= customer.delivery_note %></td>
          <td><%= customer.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<div class="div-center">
  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="/districts">Bezirke</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/newspapers">Zeitungen</a>
    </li>
  </ul>
  <br>
  <h4>Neuen Kunden erstellen</h4>
  <br>
  <%= render 'form', customer: @customer %>
  <br>
  <%= link_to 'Zurück', district_customers_path, class: "btn btn-outline-secondary" %>
</div>

app/views/districts/index.html.erb
<div class="div-center">
  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" href="/districts">Bezirke</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/newspapers">Zeitungen</a>
    </li>
  </ul>
  <br>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Bezirk ID</th>
        <th class="text-center">Abonnements</th>
        <th class="text-center">Kunden</th>
      </tr>
    </thead>
    <tbody>
      <% @districts.each do |district| %>
        <tr>
          <td><%= district.name %></td>
          <td class="text-center">
            <%= link_to "/districts/#{district.id}/subscriptions", method: :get do %>
              <i class="fas fa-newspaper"></i>
            <% end %>
          </td>
          <td class="text-center">
            <%= link_to "/districts/#{district.id}/customers", method: :get do %>
              <i class="fas fa-users"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zusteller</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <script src="https://kit.fontawesome.com/53c5385048.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/newspapers/index.html.erb
<div class="div-center">
  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="/districts">Bezirke</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="/newspapers">Zeitungen</a>
    </li>
  </ul>
  <br>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>ID</th>
      </tr>
    </thead>
    <tbody>
      <% @newspapers.each do |newspaper| %>
        <tr>
          <td><%= newspaper.full_name %></td>
          <td><%= newspaper.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subscriptions/_form.html.erb
<%= simple_form_for [@district, @subscription] do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
	  <%= form.association :customer, collection: @customers, include_blank: false, label: "Kunde:" %>
	</div>

	<div class="field">
	  <%= form.association :newspaper, as: :radio_buttons, label_method: :full_name, label: "Zeitung:" %>
	</div>

  <div class="field">
    <%= form.input :quantity, label: "Menge:" %>
  </div>

  <div class="row">
    <div class="col">
      <%= form.input :is_monday, as: :boolean, label: "MO" %>
    </div>
    <div class="col">
      <%= form.input :is_tuesday, as: :boolean, label: "DI" %>
    </div>
    <div class="col">
      <%= form.input :is_wednesday, as: :boolean, label: "MI" %>
    </div>
    <div class="col">
      <%= form.input :is_thursday, as: :boolean, label: "DO" %>
    </div>
    <div class="col">
      <%= form.input :is_friday, as: :boolean, label: "FR" %>
    </div>
    <div class="col">
      <%= form.input :is_saturday, as: :boolean, label: "SA" %>
    </div>
  </div>

  <div class="actions">
    <%= form.button :submit, "Speichern", class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/subscriptions/index.html.erb
<div class="main">
  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="/districts">Bezirke</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/newspapers">Zeitungen</a>
    </li>
  </ul>
  <br>
  
  <table>
    <tr>
      <td><h4><p class="text-dark">Abonnements des Bezirkes <%= @district.name %></p></h4></td>
      <td class="button_new"><p><%= link_to 'Neues Abonnement erstellen', new_district_subscription_path, class: "btn btn-outline-secondary" %></p></td>
    </tr>
  </table>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th></th>
        <th class="align-middle">№</th>
        <th class="align-middle">Adresse</th>
        <th class="align-middle">Name</th>
        <th class="align-middle text-center">Menge</th>
        <th class="text-center">Zeitung<br>Tage</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @subscriptions.each do |subscription| %>
        <% subscription.is_active ? status = "enabled" : status = "disabled" %>

        <% subscription.is_monday ? days_array = ["MO"] : days_array = [] %>
        <% days_array << "DI" if subscription.is_tuesday %>
        <% days_array << "MI" if subscription.is_wednesday %>
        <% days_array << "DO" if subscription.is_thursday %>
        <% days_array << "FR" if subscription.is_friday %>
        <% days_array << "SA" if subscription.is_saturday %>
        <% days_print = days_array.join(', ') %>
        <% days_bg_color = "donnerstag" if days_print == "DO" %>
        <% days_bg_color = "wochenende" if days_print == "FR" || days_print == "SA" || days_print == "FR, SA" %>
        <% days_print = "FR-SA" if days_print == "FR, SA" %>
        <% days_print = "MO-FR" if days_print == "MO, DI, MI, DO, FR" %>
        <% days_print = "" if days_array.length == 6 %>

        <tr class="align-middle">
          <td class="text-center align-middle">
            <%= link_to order_up_subscription_path(subscription), method: :post do %>
              <i class="fas fa-arrow-up"></i>
            <% end %>
            <br>
            <%= link_to order_down_subscription_path(subscription), method: :post do %>
              <i class="fas fa-arrow-down"></i>
            <% end %>
          </td>

          <td class="<%= status %> align-middle"><%= subscription.order_index/2 %></td>

          <td class="<%= status %> align-middle"><%= subscription.customer.address %><br><%= subscription.customer.delivery_note %></td>
          
          <td class="<%= status %> align-middle"><%= subscription.customer.name %></td>

          <td class="<%= status %> align-middle text-center"><%= subscription.quantity %></td>
          
          <td class="<%= status %> align-middle text-center">
            <div><%= subscription.newspaper.name %></div>
            <div class="days <%= days_bg_color %>"><%= days_print %></div>
          </td>
          
          <td class="text-center align-middle">
            <%= link_to change_status_subscription_path(subscription), method: :post do %>
              <% if subscription.is_active %>
                <i class="fas fa-toggle-on"></i>
              <% else %>
                <i class="fas fa-toggle-off"></i>
              <% end %>
            <% end %>
            &nbsp;&nbsp;
            <%= link_to subscription_path(subscription), method: :delete, data: { confirm: "Dieses Abonnement löschen?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subscriptions/new.html.erb
<div class="div-center">
  <ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="/districts">Bezirke</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/newspapers">Zeitungen</a>
    </li>
  </ul>
  <br>
  <h4>Neues Abonnement erstellen</h4>

  <%= render 'form', subscription: @subscription %>

  <br>

  <%= link_to 'Zurück', district_subscriptions_path, class: "btn btn-outline-secondary" %>
</div>